# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=25, null=True)),
                ('error', models.CharField(max_length=250, null=True)),
                ('explanation', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='error',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solve.Error'),
        ),
    ]
