# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0002_auto_20180531_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='language',
            new_name='error',
        ),
    ]
